In [1]:
with open('input.txt', 'r', encoding='utf-8') as f:
  text = f.read()

In [2]:
print("len of datasets ion characters", len(text))

len of datasets ion characters 1115394


In [3]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [4]:
#Vocab size of the text 
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [5]:
#creating a mapping from char to ints
stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("Hou u doin?"))
print(decode(encode("Hou u doin?")))

[20, 53, 59, 1, 59, 1, 42, 53, 47, 52, 12]
Hou u doin?


In [6]:
#Now we encode the entire dataset


In [17]:
#!pip install torchvision 
!pip install numpy
!pip install scipy
!pip install torch

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Python312\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Python312\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Python312\python.exe -m pip install --upgrade pip


In [18]:
import torch

data = torch.tensor(encode(text), dtype=torch.long) 
print(data.shape, data.dtype)
print(data[:1000])

ModuleNotFoundError: No module named 'torch'

In [8]:
#splititng data into training and testing set
n = int(0.9*(len(data)))
train_data = data[:n]
test_data = data[n:]

In [9]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [10]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when inpiut is {context} the target is: {target}")

when inpiut is tensor([18]) the target is: 47
when inpiut is tensor([18, 47]) the target is: 56
when inpiut is tensor([18, 47, 56]) the target is: 57
when inpiut is tensor([18, 47, 56, 57]) the target is: 58
when inpiut is tensor([18, 47, 56, 57, 58]) the target is: 1
when inpiut is tensor([18, 47, 56, 57, 58,  1]) the target is: 15
when inpiut is tensor([18, 47, 56, 57, 58,  1, 15]) the target is: 47
when inpiut is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is: 58


In [11]:
torch.manual_seed(1602)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size, ))
    x = torch.stack([data[i: i+block_size] for i in ix])
    y = torch.stack([data[i+1: i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs: ')
print(xb.shape)
print(xb)
print('targets: ')
print(yb.shape)
print(yb)
print('-----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs: 
torch.Size([4, 8])
tensor([[43, 52, 10,  0, 35, 43,  1, 51],
        [47, 58, 46,  1, 50, 53, 60, 43],
        [55, 59, 43, 39, 58, 46,  1, 58],
        [59, 56, 49, 57,  1, 61, 47, 58]])
targets: 
torch.Size([4, 8])
tensor([[52, 10,  0, 35, 43,  1, 51, 39],
        [58, 46,  1, 50, 53, 60, 43, 56],
        [59, 43, 39, 58, 46,  1, 58, 53],
        [56, 49, 57,  1, 61, 47, 58, 46]])
-----
when input is [43] the target: 52
when input is [43, 52] the target: 10
when input is [43, 52, 10] the target: 0
when input is [43, 52, 10, 0] the target: 35
when input is [43, 52, 10, 0, 35] the target: 43
when input is [43, 52, 10, 0, 35, 43] the target: 1
when input is [43, 52, 10, 0, 35, 43, 1] the target: 51
when input is [43, 52, 10, 0, 35, 43, 1, 51] the target: 39
when input is [47] the target: 58
when input is [47, 58] the target: 46
when input is [47, 58, 46] the target: 1
when input is [47, 58, 46, 1] the target: 50
when input is [47, 58, 46, 1, 50] the target: 53
when input is [47

In [17]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1602)


class BigramModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets= None):
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)

            logits = logits[:, -1, :]

            probs = F.softmax(logits, dim = -1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx
    
m = BigramModel(vocab_size)
out, loss = m(xb, yb)
print(out.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65])
tensor(4.7313, grad_fn=<NllLossBackward0>)

YP .gB3'xE$PVA OvcLVTdmA:E&jpw?SXkaM$aaTBSvInTpSKaktvN
LYXDL xCMw!pCdMGxLiXye:-yAqgW!A?yVABS&feZpazm


In [19]:
#now training the model

optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [26]:
batch_size = 32
for steps in range(10000):
    #sample batch of data
    xb, yb = get_batch('train')

    #evaluate loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none = True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.4624335765838623


In [29]:
print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


IOUSesund he-pere te wowhiedis w ber FI' ty juepouthond, Gicetoum e pe e fomen yeruthe y I ' iseero ton, mplit yoth, gou oyforeaglie tliventhucove k athy ivinow ang in, onggand f I owo;
I enonemothetatorosct
RI,
Wrke hid
Theimer w,
And chaburat phirof d y; nd fofour yber.
IUTEilowhe d a hade and:
Hou spyow amyepss bevind t wind d w y?
Hanowrd geeldy thed me adilig, t d LERYote our Sa fuirsans ch rarust im ayovit ho.
Byoonder woncore mmagat, he tuther, tomy'e.
Heru ailllicotherdy y Hafuress m pr 


In [ ]:
#now we want the tokens to talk to each other so that they can figure out hat is goin g on in the contex